name: Build APK

on:
  workflow_dispatch:

jobs:
  setup_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Gunakan versi Flutter terbaru

      - name: Debug Directory
        run: ls -la  # Cek isi direktori untuk debugging

      - name: Create Flutter Project if Missing
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "⚠️ WARNING: pubspec.yaml not found. Creating a new Flutter project..."
            flutter create .
          else
            echo "✅ Flutter project found."
          fi

      
      - name: Analyze Code
        run: flutter analyze

      - name: Build APK
        run: |
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
